server {
  listen 80;

  include /etc/nginx/mime.types;

  root /usr/share/nginx/html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /landing-page {
    rewrite ^/landing-page/?(.*)$ /$1 last;
  }
}